### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by LOTRotaconLOTR** [casperlofgren/stream-bot#2]
im tryring to install your bot. With 0 experience i manage to get through some errors but im stuck at Framework error when i install npm.

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Syzygy\Desktop\stream-bot-master\node_modules\ref
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:ref@1.3.2 ref@1.3.2 install: `node-gyp rebuild`
npm WARN install:ref@1.3.2 Exit status 1

**Comment by csprl** [comment]
From what I can tell it looks like there's a problem with the "ref" package and not the bot itself. However the code is starting to get old, and right now I don't have the time to upgrade it, so I suggest that you look for alternatives for the time being.
