### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ghost** [casperlofgren/stream-bot#3]
I know you said you weren't updating this anymore, but I'm hoping you can still help me. I'm getting this when I npm install. 

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeffr\Desktop\stream-bot\node_modules\ref
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by csprl** [comment]
Your problem is right on the second line, it can't find python! There's multiple ways to fix it, if you already have it installed (have to be 2.7.x to work with node-gyp) you can add it to your PATH, otherwise you can follow the steps in [node-gyp's README](https://github.com/nodejs/node-gyp#installation). Running `npm install --global --production windows-build-tools` should be enough.

**Comment by ghost** [comment]
As far as I can tell npm install worked after doing what you said, and when I run node index.js it says "bot is up and running in 31 channels". I put my info in config.json, but how do I get the bot to actually join my server?

**Comment by csprl** [comment]
Unfortunately there's no way to do it with code if I recall correctly, but you can log in on Discord's web client and join it from there. This code still uses a regular Discord account and not a bot token, and Discord doesn't support nor want you to use this approach. Updating the code to use the recommended authentication and a bot user isn't very hard and shouldn't take long, and if you really want I can spend some time updating it :).
